In [65]:
import pandas as pd
from pathlib import Path
import hvplot.pandas

In [78]:
# Data collection from the repository
csv_path = Path (r"C:\Users\nnroc\OneDrive\Documents\Fintech Course\Project 1\Vehicle Recalls\Resources\vrdb_60days_daily.csv")
vehicle_recalls_df = pd.read_csv(csv_path)
vehicle_recalls_df.head()

,RECALL_NUMBER_NUM,YEAR,MANUFACTURER_RECALL_NO_TXT,CATEGORY_ETXT,CATEGORY_FTXT,MAKE_NAME_NM,MODEL_NAME_NM,UNIT_AFFECTED_NBR,SYSTEM_TYPE_ETXT,SYSTEM_TYPE_FTXT,NOTIFICATION_TYPE_ETXT,NOTIFICATION_TYPE_FTXT,COMMENT_ETXT,COMMENT_FTXT,RECALL_DATE_DTE,LAST_UPDATE_DATE,MANUFACTURER_NAME_NM
0,2014299,2000,NaN,Car,Voiture,BMW,3 SERIES,"40,915.00",Airbag,Coussin gonflable,Safety Mfr,Sécurité - fabricant,"On certain vehicles, the passenger (frontal) a...","Sur certains véhicules, le générateur de gaz d...",2014-07-16,2023-01-09,BMW
1,2014299,2001,NaN,Car,Voiture,BMW,3 SERIES,"40,915.00",Airbag,Coussin gonflable,Safety Mfr,Sécurité - fabricant,"On certain vehicles, the passenger (frontal) a...","Sur certains véhicules, le générateur de gaz d...",2014-07-16,2023-01-09,BMW
2,2014299,2002,NaN,Car,Voiture,BMW,3 SERIES,"40,915.00",Airbag,Coussin gonflable,Safety Mfr,Sécurité - fabricant,"On certain vehicles, the passenger (frontal) a...","Sur certains véhicules, le générateur de gaz d...",2014-07-16,2023-01-09,BMW
3,2014299,2003,NaN,Car,Voiture,BMW,3 SERIES,"40,915.00",Airbag,Coussin gonflable,Safety Mfr,Sécurité - fabricant,"On certain vehicles, the passenger (frontal) a...","Sur certains véhicules, le générateur de gaz d...",2014-07-16,2023-01-09,BMW
4,2014299,2004,NaN,Car,Voiture,BMW,3 SERIES,"40,915.00",Airbag,Coussin gonflable,Safety Mfr,Sécurité - fabricant,"On certain vehicles, the passenger (frontal) a...","Sur certains véhicules, le générateur de gaz d...",2014-07-16,2023-01-09,BMW

In [79]:
# data cleaning
# remove unwanted columns
vehicle_recalls_df = vehicle_recalls_df.drop(columns=["RECALL_NUMBER_NUM", "MANUFACTURER_RECALL_NO_TXT", "CATEGORY_FTXT", "SYSTEM_TYPE_FTXT", "NOTIFICATION_TYPE_FTXT", "COMMENT_ETXT", "COMMENT_FTXT"])
# remove duplicates
vehicle_recalls_df = vehicle_recalls_df.drop_duplicates().copy()
# remove , in the number fields
vehicle_recalls_df["UNIT_AFFECTED_NBR"] = vehicle_recalls_df["UNIT_AFFECTED_NBR"].str.replace(",", "")
# convert the data type of number of unit from string to float
vehicle_recalls_df["UNIT_AFFECTED_NBR"] = vehicle_recalls_df["UNIT_AFFECTED_NBR"].astype('float')
# convert the data type of number of unit from float to integer
vehicle_recalls_df["UNIT_AFFECTED_NBR"] = vehicle_recalls_df["UNIT_AFFECTED_NBR"].astype('int')
#display the sample data
vehicle_recalls_df.head()

,YEAR,CATEGORY_ETXT,MAKE_NAME_NM,MODEL_NAME_NM,UNIT_AFFECTED_NBR,SYSTEM_TYPE_ETXT,NOTIFICATION_TYPE_ETXT,RECALL_DATE_DTE,LAST_UPDATE_DATE,MANUFACTURER_NAME_NM
0,2000,Car,BMW,3 SERIES,40915,Airbag,Safety Mfr,2014-07-16,2023-01-09,BMW
1,2001,Car,BMW,3 SERIES,40915,Airbag,Safety Mfr,2014-07-16,2023-01-09,BMW
2,2002,Car,BMW,3 SERIES,40915,Airbag,Safety Mfr,2014-07-16,2023-01-09,BMW
3,2003,Car,BMW,3 SERIES,40915,Airbag,Safety Mfr,2014-07-16,2023-01-09,BMW
4,2004,Car,BMW,3 SERIES,40915,Airbag,Safety Mfr,2014-07-16,2023-01-09,BMW

In [80]:
# specify the column that contains the recall date
date_col = 'RECALL_DATE_DTE'

# sort the dataframe by the recall date in descending order
vehicle_recalls_df = vehicle_recalls_df.sort_values(by=date_col, ascending=False)

# display the most recent recalls
display(vehicle_recalls_df.head())

,YEAR,CATEGORY_ETXT,MAKE_NAME_NM,MODEL_NAME_NM,UNIT_AFFECTED_NBR,SYSTEM_TYPE_ETXT,NOTIFICATION_TYPE_ETXT,RECALL_DATE_DTE,LAST_UPDATE_DATE,MANUFACTURER_NAME_NM
1931,2024,Heavy Trailer,ABS TRAILERS / ABS REMORQUES,RC,866,Structure,Safety TC,2023-01-13,2023-01-17,MANAC
1919,2019,Heavy Trailer,ABS TRAILERS / ABS REMORQUES,WC,866,Structure,Safety TC,2023-01-13,2023-01-17,MANAC
1908,2014,Heavy Trailer,ABS TRAILERS / ABS REMORQUES,RC,866,Structure,Safety TC,2023-01-13,2023-01-17,MANAC
1909,2014,Heavy Trailer,ABS TRAILERS / ABS REMORQUES,WC,866,Structure,Safety TC,2023-01-13,2023-01-17,MANAC
1911,2015,Heavy Trailer,ABS TRAILERS / ABS REMORQUES,WC,866,Structure,Safety TC,2023-01-13,2023-01-17,MANAC

In [81]:
# select only recall date and make name
vehicle_recalls_df = vehicle_recalls_df[["RECALL_DATE_DTE", "MAKE_NAME_NM"]]

# sorted data by year
vehicle_recalls_df = vehicle_recalls_df.sort_values("RECALL_DATE_DTE", ascending = False)

#display the sample data
vehicle_recalls_df.head()

     RECALL_DATE_DTE                   MAKE_NAME_NM
1931      2023-01-13  ABS TRAILERS /  ABS REMORQUES
1920      2023-01-13  ABS TRAILERS /  ABS REMORQUES
1919      2023-01-13  ABS TRAILERS /  ABS REMORQUES
1922      2023-01-13  ABS TRAILERS /  ABS REMORQUES
1924      2023-01-13  ABS TRAILERS /  ABS REMORQUES

In [82]:
vehicle_recalls_df = vehicle_recalls_df.groupby(["RECALL_DATE_DTE"]).count()

In [83]:
vehicle_recalls_df = vehicle_recalls_df.sort_values("RECALL_DATE_DTE", ascending = False)

In [84]:
vehicle_recalls_df.head()

                 MAKE_NAME_NM
RECALL_DATE_DTE
2023-01-13                 24
2023-01-11                 12
2023-01-06                 16
2023-01-03                  6
2022-12-30                 33

In [85]:
vehicle_recalls_df = vehicle_recalls_df.reset_index()

In [86]:
vehicle_recalls_df = vehicle_recalls_df[vehicle_recalls_df.RECALL_DATE_DTE> '2022-09-30']

In [87]:
vehicle_recalls_df

   RECALL_DATE_DTE  MAKE_NAME_NM
0       2023-01-13            24
1       2023-01-11            12
2       2023-01-06            16
3       2023-01-03             6
4       2022-12-30            33
5       2022-12-29             3
6       2022-12-28             4
7       2022-12-27             7
8       2022-12-23             6
9       2022-12-22            60
10      2022-12-21             1
11      2022-12-20            18
12      2022-12-19            16
13      2022-12-16            47
14      2022-12-15            43
15      2022-12-14             5
16      2022-12-13            48
17      2022-12-12            28
18      2022-12-08           111
19      2022-12-07            15
20      2022-12-06            15
21      2022-12-05             9
22      2022-12-02             6
23      2022-12-01             4
24      2022-11-30             1
25      2022-11-29            12
26      2022-11-28            21
27      2022-11-25             4
28      2022-11-24             1
29      2022-11-23            48
30      2022-11-22            16
31      2022-11-21            20
32      2022-11-19             5
33      2022-11-18             9
34      2022-11-17             1
35      2022-11-16            46
36      2022-11-15            26
37      2022-11-11             5
38      2022-11-10            19
39      2022-11-09             1
40      2022-11-08             2
41      2022-11-04             4
42      2022-11-03             5
43      2022-11-02            16
44      2022-11-01            21
45      2022-10-31             1
46      2022-10-28             5
47      2022-10-27            14
48      2022-10-26            36
49      2022-10-25            16
50      2022-10-24             1
51      2022-10-21             6
52      2022-10-07            15
53      2022-10-06            27

In [88]:
vehicle_recalls_df.hvplot.bar(
        y="MAKE_NAME_NM",
        x="RECALL_DATE_DTE",
        width=2*1024, height=512+256,
        xlabel="Date", ylabel="Number of recalls",
        title="Number of vehicle recalls by make in the last quarter",
        fontsize={'title': '35pt', 'ylabel': '25px',
                'xlabel': '25px', 'ticks': 20},
        ylim=(0, 115),
        color=["#0000FF"],
        padding=0.4,
        yformatter="%.0f",
    ).opts(xrotation=45)

:Bars   [RECALL_DATE_DTE]   (MAKE_NAME_NM)